name: Checks
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Set Up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install Ruff
        run: pip3 install ruff==0.1.3
      - name: Run Ruff Check
        run: ruff check .
      - name: Run Ruff Format
        run: ruff format . --check
  prettier:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "18.18.0"
      - name: Install Prettier
        run: npm install -g prettier
      - name: Run Prettier
        run: prettier . --check
