name: Formatting
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Set Up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.2"
      - name: Install Black
        run: pip3 install black==19.10b0
      - name: Run Black
        run: black . --check
  prettier:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12.18.1"
      - name: Install Prettier
        run: |
          npm install -g prettier
      - name: Run Prettier
        run: prettier . --check
