name: Security
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  bandit:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Set Up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.2"
      - name: Install Bandit
        run: pip3 install bandit==1.6.2
      - name: Run Bandit
        run: bandit -r . --exclude "lib,.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg"
